# Use postgres/example user/password credentials

services:
  db:
    image: postgis/postgis
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER : ${DB_USER}
      POSTGRES_DB : ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
