package fr.uge.net.medusa.api;

import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;
import java.util.concurrent.TimeUnit;

/**
 * ApiClient is responsible for configuring and creating
 * the Retrofit networking system used by the Android app.
 * This class:
 * - stores the backend server base URL
 * - configures the OkHttp HTTP client
 * - enables HTTP request/response logging
 * - configures request timeout settings
 * - enables automatic JSON conversion using Gson
 * - creates the Retrofit instance
 * - creates the ApiService implementation used to call API endpoints
 *
 * Retrofit and OkHttp are created only once and reused
 * throughout the application for better performance.
 */
public class ApiClient {
    // Use 10.0.2.2 for Android emulator, or your machine's IP for physical device
    private static final String BASE_URL = "http://10.0.2.2:3000/";
    private static Retrofit retrofit;

    public static Retrofit getClient() {
        if (retrofit == null) {
            // Add logging interceptor for debugging
            HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
            loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

            // Configure OkHttp client
            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .addInterceptor(loggingInterceptor)
                    .connectTimeout(30, TimeUnit.SECONDS)       //Maximum time allowed to establish connection.
                    .readTimeout(30, TimeUnit.SECONDS)          //Maximum wait time for server response data.
                    .writeTimeout(30, TimeUnit.SECONDS)         //Maximum time allowed to send request body.
                    .build();

            /* Build Retrofit instance which wil:
             * - send HTTP requests
             * - receive responses
             * - convert JSON into Java objects using Gson
             */
            retrofit = new Retrofit.Builder()
                    // Base backend server URL
                    .baseUrl(BASE_URL)
                    // Use configured OkHttp client
                    .client(okHttpClient)
                    // Enable automatic JSON conversion
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        }
        return retrofit;
    }

    /**
     * Retrofit automatically creates the implementation
     * of the ApiService interface.
     * @return the ApiService implementation generated by Retrofit.
     */
    public static ApiService getApiService() {
        return getClient().create(ApiService.class);
    }
}